config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :services, path: 'servicos' do
      member do
        put 'like', to: 'services#upvote'
        put 'dislike', to: 'services#downvote'
      end
    end
  end

  get 'dashboard', to: 'dashboard#index'

  get 'state/:id', to: 'states#show', format: 'json'

  get 'area/:area_id/subareas', to: 'application#load_subareas', as: 'subareas', format: :json

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'welcome#index'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_error', via: :all

  post 'reports', to: 'reports#create', as: 'report'
  match 'list/services_with_reports', to: 'lists#services_with_reports', via: :all
  get 'reports/:service_id', to: 'reports#find_reports_by_service', as: 'reports_by_service'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
end

app/views/welcome/index.html.erb
<header id="main-header">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
				<h1 class="text-center">
					<%= image_tag 'transervicos-logo.svg', alt: 'Transerviços' %>
				</h1>
				<div class="lead text-center">
                    <div class="col-sm-6 text-center cadastre-busque">
    					<p>Você gostaria de cadastrar algum serviço que não discrimine as pessoas
    						trans e travestis?</p>
                        <% if !user_signed_in? %><%= link_to 'cadastre-se', new_user_registration_path, { :class=>"btn-contorno" } %>
                        <% else %>
                        <%= link_to 'Cadastre serviço', new_service_path, { :class=>"btn-contorno" } %>
                        <% end %>
                    </div>
                    <div class="hidden-sm hidden-md hidden-lg mobile-separator"></div>
                    <div class="col-sm-6 text-center cadastre-busque">
                        <p>Você está em busca de serviços oferecidos por essas pessoas ou que não as discriminem?</p>
    					<div class="cadastre-busque">
    						<%= link_to 'busque serviços', services_path, { :class=>"btn-contorno" } %>
    					</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</header>

<section id="trans-hoje">
	<a name="trans-hoje"></a>
	<div class="container">
		<div class="row">
			<div class="col-md-4 text-center">
				<h2 class="brazil">Como é ser trans ou travesti no Brasil hoje?</h2>
				<p>
					O Brasil é o país campeão mundial de assassinatos de travestis e transexuais.
					A discriminação faz com que a grande maioria dessas pessoas não consiga
					completar seus estudos e esteja fora do mercado de trabalho formal.
				</p>
				<!--<a href="javascript:;">Saiba mais</a>-->
			</div>
			<div class="col-md-4 text-center">
				<h2 class="rights">Direitos que, por lei, deveríamos ter</h2>
				<p>
					Aprovação de uma lei de identidade de gênero para que as pessoas trans
					e travestis possam modificar seus documentos sem grandes burocracias,
					direito ao emprego, acesso ao sistema de saúde, leis de proteção contra
					a transfobia, dentre outros.
				</p>
				<!--<a href="javascript:;">Saiba mais</a>-->
			</div>
			<div class="col-md-4 text-center">
				<h2 class="change">O que eu posso fazer para mudar isso?</h2>
				<p>
					Que tal contratar uma das talentosas pessoas trans e travestis que anunciam
					nesse site? E caso você conheça algum serviço que é verdadeiramente
					respeitoso com as pessoas trans e travestis, que tal publicá-lo aqui?
				</p>
				<!--<a href="javascript:;">Saiba mais</a>-->
			</div>
		</div>
	</div>
</section>

<section id="desconstruindo-mitos">
  <a name="desconstruindo-mitos"></a>
  <div class="container">
    <h1 class="text-center">
      <%= t('.carousel.header').html_safe %>
    </h1>

    <div class="row carousel">
      <div class="col-sm-6 col-lg-5 col-lg-offset-1">
        <%= image_tag 'trans-people.svg', { :class=>"img-responsive", :alt=>"Ilustração de pessoas trans" } %>
      </div>

      <div class="col-sm-6 col-lg-5">
        <div class="mitos-controle control text-right">
          <i class="fa fa-lg fa-circle active" data-m="1"></i>
          <i class="fa fa-lg fa-circle" data-m="2"></i>
          <i class="fa fa-lg fa-circle" data-m="3"></i>
        </div>

        <div class="carousel-container">
          <div class="mito carousel-element" data-m="1">
            <p class="lead text-fuchsia"><%= t('.carousel.myth') %></p>
            <h2>
              <%= t('.carousel.elements.first.myth_explain') %>
            </h2>

            <p class="lead text-fuchsia"><%= t('.carousel.fact') %></p>

            <%= t('.carousel.elements.first.fact_explain').html_safe %>
          </div>

          <div class="mito carousel-element" data-m="2" style="display:none">
            <p class="lead text-fuchsia"><%= t('.carousel.myth') %></p>

            <h2>
              <%= t('.carousel.elements.second.myth_explain') %>
            </h2>

            <p class="lead text-fuchsia"><%= t('.carousel.fact') %></p>

            <%= t('.carousel.elements.second.fact_explain').html_safe %>
          </div>

          <div class="mito carousel-element" data-m="3" style="display:none">
            <p class="lead text-fuchsia"><%= t('.carousel.myth') %></p>

            <h2>
              <%= t('.carousel.elements.third.myth_explain') %>
            </h2>
            <p class="lead text-fuchsia"><%= t('.carousel.fact') %></p>

            <%= t('.carousel.elements.third.fact_explain').html_safe %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>